### ISSUE TITLE
请问为什么安装了node和git拿到源码编译之后运行报错?新手还请指导一下,谢谢

### ISSUE THREAD

**Issue by wadjsnkk** [Fuck-You-GFW/p2pspider#20]
[root@localhost w]# node p2pspider/test/index.js 
events.js:24
  this.domain = null;
              ^

TypeError: Cannot set property 'domain' of undefined
    at EventEmitter.init (events.js:24:15)
    at EventEmitter (events.js:6:21)
    at P2PSpider (/root/w/p2pspider/lib/index.js:10:18)
    at Object.<anonymous> (/root/w/p2pspider/test/index.js:5:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)

**Comment by Fuck-You-GFW** [comment]
`node` 版本号要`0.12.0`以上 才可以, `README.md` 里有说明. 你可用 `nvm` 来管理 `node` 版本号.

**Comment by wadjsnkk** [comment]
你好,感谢您的回答,但是我的版本是[root@localhost w]# node -v
v4.3.2了 这里的报错是this.domain = null;是不是我还要配置什么文件才可以启动?

**Comment by Fuck-You-GFW** [comment]
我帮你查了下, 是`node`的问题, 详情见[https://github.com/nodejs/node-v0.x-archive/issues/7550](https://github.com/nodejs/node-v0.x-archive/issues/7550)

解决之道: 不用`node 4.3.2`, 换其他的版本, 最简单粗暴的方法是, 换到最新版即可.

**Comment by wadjsnkk** [comment]
额,你好问题解决了,我用最新版的的也不行,但是我用了0.12.1就可以了,谢谢.

**Comment by Fuck-You-GFW** [comment]
你好, 我仔细看了下我代码, 大部分是我的问题. 我已经修复了, 你可重新`git pull`, 你的`node 4.3.2`  也能正常执行了.

非常感谢你这个很重要的issue!
