### ISSUE TITLE
在CentOS，node6.0环境下报错

### ISSUE THREAD

**Issue by lytofb** [Fuck-You-GFW/p2pspider#54]
RT，正常clone工程后使用node test/index.js运行报错

util.js:556
  ctor.prototype = Object.create(superCtor.prototype, {
                          ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.exports.inherits (util.js:556:27)
    at Object.<anonymous> (/home/git_clone/p2pspider/lib/btclient.js:30:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/git_clone/p2pspider/lib/index.js:7:16)

**Comment by lytofb** [comment]
不知道怎么又好用了。。
